# Generated by Django 5.1.7 on 2025-05-13 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.ImageField(upload_to='book_covers/')),
                ('book_name', models.CharField(max_length=255)),
                ('book_description', models.TextField()),
                ('genres', models.CharField(max_length=255)),
                ('book_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('author', models.CharField(default='Unknown Author', max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
