# Generated by Django 5.1.7 on 2025-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorder', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='Old', max_length=10),
        ),
    ]
