# Generated by Django 5.1.7 on 2025-03-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='shipping_address',
        ),
    ]
