# Generated by Django 5.1.7 on 2025-06-07 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_buyerprofile_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('corporate', 'Corporate')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
