# Generated by Django 5.1.7 on 2025-06-07 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_corporatesellerprofile_personalsellerprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatesellerprofile',
            options={'verbose_name': 'Corporate Seller Profile', 'verbose_name_plural': 'Corporate Seller Profiles'},
        ),
        migrations.AlterModelOptions(
            name='personalsellerprofile',
            options={'verbose_name': 'Personal Seller Profile', 'verbose_name_plural': 'Personal Seller Profiles'},
        ),
        migrations.RemoveField(
            model_name='corporatesellerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='corporatesellerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personalsellerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personalsellerprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('personal', 'Personal'), ('corporate', 'Corporate')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
            },
        ),
        migrations.AddField(
            model_name='corporatesellerprofile',
            name='sellerprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.sellerprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalsellerprofile',
            name='sellerprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.sellerprofile'),
            preserve_default=False,
        ),
    ]
